services:
  postgres:
    image: postgres:16-alpine
    container_name: postkasir-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postkasir
      POSTGRES_PASSWORD: postkasir123
      POSTGRES_DB: postkasir
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
